fix: set isReachEnd
naver/egjs-conveyer pull request #13
Opened 2022-05-26 08:58 UTC by henrysha

## Details

isReachEnd has bugs of being true when the scroll has reached the end on some device
This is due to a bug in the scrollLeft on some device of having a decimal value
In order to prevent the bug, this fix adds additional calculation.
When `scrollSize - size - pos < 1`, it means the scroll has reached the end, but has a decimal scrollLeft value.
Thus, it would be safe to assume, that it has reached the end if the above condition returns true

2022-05-27 03:08 UTC, daybrush approved these changes
LGTM

2022-05-27 03:10 UTC, daybrush commented on packages/conveyer/src/Conveyer.ts
> +    if ((pos >= scrollSize - size || scrollSize - size - pos < 1) && this.isReachEnd !== true) {
If there is only one condition "scrollSize - size - pos < 1", the condition seems to be the same.

2022-05-27 08:58 UTC, malangfox approved these changes
LGTM

2022-05-27 09:09 UTC, WoodNeck requested changes
Maybe it should be fixed like `pos > scrollSize - size - 1 && pos <= scrollSize - size` or sth.
But shouldn't the offset be `0.5` or some well-tested value?
Setting the maximum offset as `1` may create 1px gap.

2022-06-02 02:08 UTC, henrysha commented
@WoodNeck I have googled about this issue, and some people on stack overflow are mentioning the scrollLeft values being .6667 or .8 etc. I don't think it is safe to assume that the decimal value will always be .5, since this value varies upon devices and browser.

2022-06-02 02:09 UTC, henrysha commented on packages/conveyer/src/Conveyer.ts
> +    if ((pos >= scrollSize - size || scrollSize - size - pos < 1) && this.isReachEnd !== true) {
```suggestion
    if (scrollSize - size - pos < 1 && this.isReachEnd !== true) {
```

2022-06-02 02:10 UTC, henrysha commented
\+ It seems this PR needs approval to run the workflow

2022-06-02 02:32 UTC, WoodNeck commented
@henrysha
I didn't say the decimal value is always `0.5`, but the "**offset**" from the end should be 0.5 or some well-tested value.

Let's say the `pos`(scrollLeft) is `99.2`.
When it's rendered, the position would be rounded to pixel `99`,
but it still passes our if-statement, as `scrollSize - size - pos` will be `0.8`

Have you tested it doesn't cause this kind of 1px offset issue?

2022-06-02 02:37 UTC, henrysha commented
@WoodNeck On my use cases, the maximum scrollLeft I could reach was `233.5` but the `scrollWidth - clientWidth` was equal to `234`. This caused `isReachEnd` to always be false.

Upon searching for answers, I found
> Warning: On systems using display scaling, scrollLeft may give you a decimal value.
https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollLeft

the above from MDN.
Thus, I concluded that decimal values should be rounded up instead of being rounded down for proper calculation.

2022-06-02 03:07 UTC, WoodNeck commented
@henrysha 
I mean, have you tested the case of `233.2`? You should test the values where decimal value is `0 < val < 0.5`

2022-06-02 03:07 UTC, WoodNeck approved these changes
@daybrush 
Please add the tests if you think it's needed.

2022-06-02 03:27 UTC, daybrush commented
@malangfox 

I think you can proceed.

2022-06-02 03:57 UTC, merged